#!/usr/bin/env python3

class COLOR:
    NONE = "\033[0m" # No Color

    GREEN = "\033[0;32m"
    RED = "\033[0;31m"
    WHITE = "\033[1;97m"

    LIGHT_GREEN = "\033[1;92m"
    LIGHT_RED = "\033[1;91m"
    LIGHT_YELLOW = "\033[1;93m"
    LIGHT_WHITE = "\033[1;97m"

ERROR = COLOR.LIGHT_RED + "Error" + COLOR.NONE
FAILED = COLOR.LIGHT_RED + "Failed" + COLOR.NONE
OK = COLOR.LIGHT_GREEN + "Ok" + COLOR.NONE
SUCCESS = COLOR.LIGHT_GREEN + "Success" + COLOR.NONE
WARNING = COLOR.LIGHT_YELLOW + "Warning" + COLOR.NONE
